# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-19 23:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('date_from', models.DateField()),
                ('date_to', models.DateField()),
                ('created_at', models.DateField()),
                ('updated_at', models.DateField()),
                ('joined_by', models.ManyToManyField(related_name='join_to', to='login.User')),
                ('users', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='added_by', to='login.User')),
            ],
        ),
        migrations.CreateModel(
            name='TripManager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
